### ISSUE TITLE
Uploaded versions not shown

### ISSUE THREAD

**Issue by mewolari** [goldsky/GridClassKey#127]
The Grid Class Key package is not shown in uploaded versions in package management. Deleting older versions is not possible in the manager.

![grid class key](https://cloud.githubusercontent.com/assets/2721621/6564751/6ad26adc-c6ab-11e4-8b2a-1ab22e79166e.jpg)

**Comment by goldsky** [comment]
Oh, this is an old problem since its birth.
I named this package using spaces, but MODX doesn't deal with it.
http://forums.modx.com/thread/88734/package-version-check

**Comment by goldsky** [comment]
duplicate https://github.com/goldsky/GridClassKey/issues/132
