### ISSUE TITLE
No shows  Modx 2.3.3 problems

### ISSUE THREAD

**Issue by TITAN-UZ** [goldsky/GridClassKey#128]
Hello!
no shows title, Advanced title, description

gridclasskey-1.0.1-rc3

http://s38-temporary-files.radikal.ru/f8fa653c627e4ffd8e4a412852aed07b/-929206895.png

**Comment by TITAN-UZ** [comment]
Hello
When approximately correct the problem, do not want to install another plugin

**Comment by TITAN-UZ** [comment]
\core\components\gridclasskey\processors\mgr\classkey\children\getlist.class.php : 278) PHP warning: Invalid argument supplied for foreach()

**Comment by vierkantemeter** [comment]
Did you get these errors after upgrading MODX 2.2 to 2.3? I did, and after removing all fields except pagetitle, everything was working again. After that, you can add all removed fields again.

**Comment by vhollo** [comment]
It's enough to make some reordering on the grid to get it working.

**Comment by goldsky** [comment]
The new 2.3.+ version stores something on its &reload parameter.
The solution is just by saving the resource, which means clearing MODX's &reload parameter.
