### ISSUE TITLE
Versions not shown in "uploaded versions"

### ISSUE THREAD

**Issue by mewolari** [goldsky/GridClassKey#132]
Actual and older versions of GridClassKey are not shown in "uploaded versions"  in the Installer in the MODX manager.

Not able to remove older versions in the Manager. Other Extras are working fine.

**Comment by goldsky** [comment]
https://github.com/modxcms/revolution/pull/11125

**Comment by goldsky** [comment]
https://github.com/modxcms/revolution/pull/12870
