### ISSUE TITLE
Resource deletion and caching [$12]

### ISSUE THREAD

**Issue by vierkantemeter** [goldsky/GridClassKey#133]
I have some strange issue with deleted documents. I guess it's caching related.

The situation:
- Create a resource in a GCK container
- Right click on resource > delete > confirm
- Resource gets a red 'deleted' line
- Move away from GCK container
- Click the trash can
- Go back to GCK container: the deleted resource is back in the list as unpublished, but it's deleted from the database table modx_site_content
- When I clear the cache, the resource is really gone.

I hope you can check this out!

MODX 2.4.0
GCK 1.0.1 rc3

**Comment by vierkantemeter** [comment]
It's a bug I really would like to have fixed. I've added a bounty for you.

**Comment by goldsky** [comment]
ok, I'll check on this asap

**Comment by goldsky** [comment]
I'm using MODX 2.4.2, and it seems the problem is no longer existed?

**Comment by vierkantemeter** [comment]
Hmm, updated the site to 2.4.2, and this problem still existst. If you would you like to take a look in the manager, let me know.

**Comment by goldsky** [comment]
Sure, to goldsky@virtudraft.com, please

**Comment by goldsky** [comment]
After more investigation, "cache_db" in the System Settings is the culprit.
Turning it off resolves the problem.

**Comment by vierkantemeter** [comment]
Thanks for investigating! Please take the bounty :)

When I disable cache_db, does this only affects the manager cache? Or does this setting also disables the front-end database caching? This is a bit vague.

**Comment by goldsky** [comment]
I'm not quite sure about it, but seems related
