### ISSUE TITLE
Actions Icons

### ISSUE THREAD

**Issue by eladnova** [goldsky/GridClassKey#88]
Have you considered changing the 4 icons int he Actions column to an ExtJs button like this?
http://docs.sencha.com/extjs/4.2.2/extjs-build/examples/build/KitchenSink/ext-theme-neptune/#split-buttons

**Comment by vierkantemeter** [comment]
That would be great. Also, making use of the FontAwesome icons used in MODX 2.3 to make it look more consistent.

**Comment by goldsky** [comment]
While this is intriguing, ExtJs 3.4 can not have components inside the grid.
We can re-issue this when Manager is upgraded above ExtJs 4.
